POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "cool guy cool stuff",
    "author": "Cool Guy 3",
    "url": "www.coolstuff3.com",
    "likes": 10, 
    "userId": "610c9f52b840cad43aa61972"
}

###
DELETE http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc

###
PUT http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc
Content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 10
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "mstewart",
    "name": "Martha Stewart",
    "password": "smokeweed"
}