POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Cool Guy 3",
    "url": "www.coolstuff3.com",
    "likes": 10 
}

###
DELETE http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc