POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "cool guy cool stuff",
    "author": "Cool Guy 3",
    "url": "www.coolstuff3.com",
    "likes": 10, 
    "userId": "610d6eff919c47db586f52ff"
}

###
DELETE http://localhost:3003/api/blogs/610d762980438bde68cdef89
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNkb2czIiwiaWQiOiI2MTBkNmYyMTkxOWM0N2RiNTg2ZjUzMDQiLCJpYXQiOjE2MjgyNzIwOTZ9.bmrfTPVWS0LzWGUbaU6RgRemoqaZqVTfhvObNUrzo_w


###
PUT http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc
Content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 10
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "myoung",
    "name": "Michael Young",
    "password": "password"
}


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sdog3",
    "password": "smokeweed"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNkb2czIiwiaWQiOiI2MTBkNmYyMTkxOWM0N2RiNTg2ZjUzMDQiLCJpYXQiOjE2MjgyNzIwOTZ9.bmrfTPVWS0LzWGUbaU6RgRemoqaZqVTfhvObNUrzo_w

{
    "title": "cool guy cool stuff 15",
    "author": "Cool Guy 3",
    "url": "www.coolstuff15.com",
    "likes": 10
}

###
POST http://localhost:3003/api/blogs/6115b9f03f9cc1d679ce4f04/comments
Content-Type: application/json

{
    "blog": {
        "title": "apples are good",
        "url": "www.apple.com",
        "likes": "46",
        "author": "Steve Jobs 2",
        "user": {
            "username": "myoung",
            "name": "Michael Young",
            "id": "6115b9ef3f9cc1d679ce4ef1"
        },
        "id": "6115b9f03f9cc1d679ce4f04",
        "comments": []
    },
    "comment": "hi mom"
}
